import Head from "next/head";
import Image from "next/image";
// icon
import { MenuIcon } from "@heroicons/react/solid";
// img
import img_logo from "../public/yohei_logo.svg";

export default function Home() {
  return (
    <div className="prose max-w-none antialiased">
      <Head>
        <title>My portfolio</title>
        <meta name="description" content="Generated by Yohei Shiina" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* full screen in both height and width */}
      <div className="h-screen w-screen">
        {/* Header */}
        <div className="nav pt-5 px-5">
          <div className="flex justify-between">
            <div className="flex">
              {/* icon */}
              <div>
                <Image alt="logo" src={img_logo} width="45" height="45" />
              </div>
              {/* name and job */}
              <div>
                <div className="ml-2 text-xl font-semibold">Yohei Shiina</div>
                <div className="ml-3 text-xs">System Engineer</div>
              </div>
            </div>
            {/* Todo: implement later*/}
            <MenuIcon className="flex" width="50" height="50" />
          </div>
        </div>
        {/* background image picture myself */}
        <div className="bg-myself absolute h-2/3 md:h-screen w-screen md:w-1/3 bg-right md:right-10% bg-contain bg-no-repeat -z-10"></div>
        {/* background image word engineering */}
        <div className="bg-engineering absolute md:h-250 2xl:h-300 md:w-screen bg-center bg-contain bg-no-repeat md:-z-20"></div>
        {/* section 1 */}
        <section className="container pt-72 2xl:pt-96">
          <div className="px-2 md:w-2/3">
            <div className="text-gray-500 text-sm md:text-4xl 2xl:text-5xl md:my-6 tracking-widest">
              YOHEI SHIINA
            </div>
            <div className="text-black text-4xl md:text-6xl 2xl:text-8xl md:my-6 font-semibold">
              Japanese-made web application developer
            </div>
            <p className="text-gray-500 md:text-2xl 2xl:text-3xl md:my-6">
              Over the past 3 years I’ve worked for a big programming school in
              Japan and taught more than 100 aspiring programmers and currently
              working and developing web applications for an up-and-coming
              software company.
            </p>
          </div>
        </section>
      </div>
    </div>
  );
}
